# Accessing data with pandas

In [2]:
import pandas as pd

In [3]:
coffee=pd.read_csv('./data/coffee.csv')

In [4]:
coffee.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [5]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [6]:
coffee.sample(10)

          Day Coffee Type  Units Sold
13     Sunday       Latte          35
11   Saturday       Latte          35
0      Monday    Espresso          25
7    Thursday       Latte          30
8      Friday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
4   Wednesday    Espresso          35
2     Tuesday    Espresso          30
12     Sunday    Espresso          45

In [7]:
coffee.loc[2]

Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object

In [8]:
coffee.loc[[0,1,2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [9]:
coffee.loc[0:5,["Day","Coffee Type"]]

         Day Coffee Type
0     Monday    Espresso
1     Monday       Latte
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso
5  Wednesday       Latte

In [10]:
coffee.iloc[0:5,[0,2]] #only let element  access by index.

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [11]:
coffee.index=coffee["Day"]

In [12]:
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [13]:
coffee.loc["Monday"]

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [14]:
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [15]:
coffee.loc[1,["Units Sold"]]=10

In [16]:
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso        25.0
Monday        Monday       Latte        15.0
Tuesday      Tuesday    Espresso        30.0
Tuesday      Tuesday       Latte        20.0
Wednesday  Wednesday    Espresso        35.0
Wednesday  Wednesday       Latte        25.0
Thursday    Thursday    Espresso        40.0
Thursday    Thursday       Latte        30.0
Friday        Friday    Espresso        45.0
Friday        Friday       Latte        35.0
Saturday    Saturday    Espresso        45.0
Saturday    Saturday       Latte        35.0
Sunday        Sunday    Espresso        45.0
Sunday        Sunday       Latte        35.0
1                NaN         NaN        10.0

In [ ]:
coffee.iat[0,2]

np.float64(25.0)

In [45]:
coffee.sort_values(["Units Sold","Coffee Type"],ascending=[0,1])

                 Day Coffee Type  Units Sold  price  revenue
Day
Friday        Friday    Espresso        45.0   3.99   179.55
Saturday    Saturday    Espresso        45.0   3.99   179.55
Sunday        Sunday    Espresso        45.0   3.99   179.55
Thursday    Thursday    Espresso        40.0   3.99   159.60
Wednesday  Wednesday    Espresso        35.0   3.99   139.65
Friday        Friday       Latte        35.0   6.33   221.55
Saturday    Saturday       Latte        35.0   6.33   221.55
Sunday        Sunday       Latte        35.0   6.33   221.55
Tuesday      Tuesday    Espresso        30.0   3.99   119.70
Thursday    Thursday       Latte        30.0   6.33   189.90
Monday        Monday    Espresso        25.0   3.99    99.75
Wednesday  Wednesday       Latte        25.0   6.33   158.25
Tuesday      Tuesday       Latte        20.0   6.33   126.60
Monday        Monday       Latte        15.0   6.33    94.95
1                NaN         NaN        10.0   6.33    63.30

### Filtering Data

In [46]:
bios=pd.read_csv('./data/bios.csv')

In [47]:
bios

,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [48]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    145500 non-null  int64
 1   athlete_id    145500 non-null  int64
 2   name          145500 non-null  str
 3   born_date     143693 non-null  str
 4   born_city     110908 non-null  str
 5   born_region   110908 non-null  str
 6   born_country  110908 non-null  str
 7   NOC           145499 non-null  str
 8   height_cm     106651 non-null  float64
 9   weight_kg     102070 non-null  float64
 10  died_date     33940 non-null   str
 11  first_name    144586 non-null  str
dtypes: float64(2), int64(2), str(8)
memory usage: 21.6 MB

In [49]:
bios.loc[bios['height_cm']>215,["name","height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [50]:
bios[(bios['height_cm']>180)&(bios["NOC"]=="India")][["name","height_cm"]]

                   name  height_cm
274      Anand Amritraj      185.0
275      Vijay Amritraj      193.0
276       Chetan Baboor      188.0
278     Mahesh Bhupathi      185.0
284         Vimal Kumar      184.0
...                 ...        ...
131641    Hardeep Singh      183.0
140263     Satish Kumar      188.0
140265      Udayan Mane      192.0
140268    Gurjant Singh      183.0
140276     Arvind Singh      184.0

[89 rows x 2 columns]

In [51]:
bios[bios["name"].str.contains("Neeraj",case=False)]

,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
140251,140251,143754,Neeraj Chopra,1997-12-24,NaN,NaN,NaN,India,NaN,NaN,NaN,Neeraj

In [52]:
bios[bios['born_country'].isin(["USA","IND"]) & (bios['name'].str.startswith("Sumit"))]

,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
120558,120558,122483,Sumit Sangwan,1993-01-01,Sohana,Punjab,IND,India,NaN,NaN,NaN,Sumit
143996,143996,147660,Sumit Nagal,1997-08-16,Jhajjar,Haryana,IND,India,NaN,NaN,NaN,Sumit

In [53]:
bios.query('born_country=="India" and name=="Sumit"')

Empty DataFrame
Columns: [Unnamed: 0, athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date, first_name]
Index: []

### Adding/Removing Columns from dataframe

In [54]:

coffee['Price']=5.99

In [55]:
coffee

                 Day Coffee Type  Units Sold  price  revenue  Price
Day
Monday        Monday    Espresso        25.0   3.99    99.75   5.99
Monday        Monday       Latte        15.0   6.33    94.95   5.99
Tuesday      Tuesday    Espresso        30.0   3.99   119.70   5.99
Tuesday      Tuesday       Latte        20.0   6.33   126.60   5.99
Wednesday  Wednesday    Espresso        35.0   3.99   139.65   5.99
Wednesday  Wednesday       Latte        25.0   6.33   158.25   5.99
Thursday    Thursday    Espresso        40.0   3.99   159.60   5.99
Thursday    Thursday       Latte        30.0   6.33   189.90   5.99
Friday        Friday    Espresso        45.0   3.99   179.55   5.99
Friday        Friday       Latte        35.0   6.33   221.55   5.99
Saturday    Saturday    Espresso        45.0   3.99   179.55   5.99
Saturday    Saturday       Latte        35.0   6.33   221.55   5.99
Sunday        Sunday    Espresso        45.0   3.99   179.55   5.99
Sunday        Sunday       Latte        35.0   6.33   221.55   5.99
1                NaN         NaN        10.0   6.33    63.30   5.99

In [56]:
import numpy as np

coffee['new_price']=np.where(coffee['Coffee Type']=='Espresso',3.99,6.33)

In [57]:
coffee

                 Day Coffee Type  Units Sold  price  revenue  Price  new_price
Day
Monday        Monday    Espresso        25.0   3.99    99.75   5.99       3.99
Monday        Monday       Latte        15.0   6.33    94.95   5.99       6.33
Tuesday      Tuesday    Espresso        30.0   3.99   119.70   5.99       3.99
Tuesday      Tuesday       Latte        20.0   6.33   126.60   5.99       6.33
Wednesday  Wednesday    Espresso        35.0   3.99   139.65   5.99       3.99
Wednesday  Wednesday       Latte        25.0   6.33   158.25   5.99       6.33
Thursday    Thursday    Espresso        40.0   3.99   159.60   5.99       3.99
Thursday    Thursday       Latte        30.0   6.33   189.90   5.99       6.33
Friday        Friday    Espresso        45.0   3.99   179.55   5.99       3.99
Friday        Friday       Latte        35.0   6.33   221.55   5.99       6.33
Saturday    Saturday    Espresso        45.0   3.99   179.55   5.99       3.99
Saturday    Saturday       Latte        35.0   6.33   221.55   5.99       6.33
Sunday        Sunday    Espresso        45.0   3.99   179.55   5.99       3.99
Sunday        Sunday       Latte        35.0   6.33   221.55   5.99       6.33
1                NaN         NaN        10.0   6.33    63.30   5.99       6.33

In [58]:
coffee.drop(columns="Price" ,inplace=True)

In [59]:
coffee

                 Day Coffee Type  Units Sold  price  revenue  new_price
Day
Monday        Monday    Espresso        25.0   3.99    99.75       3.99
Monday        Monday       Latte        15.0   6.33    94.95       6.33
Tuesday      Tuesday    Espresso        30.0   3.99   119.70       3.99
Tuesday      Tuesday       Latte        20.0   6.33   126.60       6.33
Wednesday  Wednesday    Espresso        35.0   3.99   139.65       3.99
Wednesday  Wednesday       Latte        25.0   6.33   158.25       6.33
Thursday    Thursday    Espresso        40.0   3.99   159.60       3.99
Thursday    Thursday       Latte        30.0   6.33   189.90       6.33
Friday        Friday    Espresso        45.0   3.99   179.55       3.99
Friday        Friday       Latte        35.0   6.33   221.55       6.33
Saturday    Saturday    Espresso        45.0   3.99   179.55       3.99
Saturday    Saturday       Latte        35.0   6.33   221.55       6.33
Sunday        Sunday    Espresso        45.0   3.99   179.55       3.99
Sunday        Sunday       Latte        35.0   6.33   221.55       6.33
1                NaN         NaN        10.0   6.33    63.30       6.33

In [60]:
coffee

                 Day Coffee Type  Units Sold  price  revenue  new_price
Day
Monday        Monday    Espresso        25.0   3.99    99.75       3.99
Monday        Monday       Latte        15.0   6.33    94.95       6.33
Tuesday      Tuesday    Espresso        30.0   3.99   119.70       3.99
Tuesday      Tuesday       Latte        20.0   6.33   126.60       6.33
Wednesday  Wednesday    Espresso        35.0   3.99   139.65       3.99
Wednesday  Wednesday       Latte        25.0   6.33   158.25       6.33
Thursday    Thursday    Espresso        40.0   3.99   159.60       3.99
Thursday    Thursday       Latte        30.0   6.33   189.90       6.33
Friday        Friday    Espresso        45.0   3.99   179.55       3.99
Friday        Friday       Latte        35.0   6.33   221.55       6.33
Saturday    Saturday    Espresso        45.0   3.99   179.55       3.99
Saturday    Saturday       Latte        35.0   6.33   221.55       6.33
Sunday        Sunday    Espresso        45.0   3.99   179.55       3.99
Sunday        Sunday       Latte        35.0   6.33   221.55       6.33
1                NaN         NaN        10.0   6.33    63.30       6.33

In [61]:
coffee

                 Day Coffee Type  Units Sold  price  revenue  new_price
Day
Monday        Monday    Espresso        25.0   3.99    99.75       3.99
Monday        Monday       Latte        15.0   6.33    94.95       6.33
Tuesday      Tuesday    Espresso        30.0   3.99   119.70       3.99
Tuesday      Tuesday       Latte        20.0   6.33   126.60       6.33
Wednesday  Wednesday    Espresso        35.0   3.99   139.65       3.99
Wednesday  Wednesday       Latte        25.0   6.33   158.25       6.33
Thursday    Thursday    Espresso        40.0   3.99   159.60       3.99
Thursday    Thursday       Latte        30.0   6.33   189.90       6.33
Friday        Friday    Espresso        45.0   3.99   179.55       3.99
Friday        Friday       Latte        35.0   6.33   221.55       6.33
Saturday    Saturday    Espresso        45.0   3.99   179.55       3.99
Saturday    Saturday       Latte        35.0   6.33   221.55       6.33
Sunday        Sunday    Espresso        45.0   3.99   179.55       3.99
Sunday        Sunday       Latte        35.0   6.33   221.55       6.33
1                NaN         NaN        10.0   6.33    63.30       6.33

In [62]:
coffee['revenue']=coffee['new_price']*coffee["Units Sold"]

In [63]:
coffee

                 Day Coffee Type  Units Sold  price  revenue  new_price
Day
Monday        Monday    Espresso        25.0   3.99    99.75       3.99
Monday        Monday       Latte        15.0   6.33    94.95       6.33
Tuesday      Tuesday    Espresso        30.0   3.99   119.70       3.99
Tuesday      Tuesday       Latte        20.0   6.33   126.60       6.33
Wednesday  Wednesday    Espresso        35.0   3.99   139.65       3.99
Wednesday  Wednesday       Latte        25.0   6.33   158.25       6.33
Thursday    Thursday    Espresso        40.0   3.99   159.60       3.99
Thursday    Thursday       Latte        30.0   6.33   189.90       6.33
Friday        Friday    Espresso        45.0   3.99   179.55       3.99
Friday        Friday       Latte        35.0   6.33   221.55       6.33
Saturday    Saturday    Espresso        45.0   3.99   179.55       3.99
Saturday    Saturday       Latte        35.0   6.33   221.55       6.33
Sunday        Sunday    Espresso        45.0   3.99   179.55       3.99
Sunday        Sunday       Latte        35.0   6.33   221.55       6.33
1                NaN         NaN        10.0   6.33    63.30       6.33

In [64]:
coffee=coffee.rename(columns={'new_price':"price"})

In [71]:
coffee.to_csv('./data/coffee.csv')

In [66]:
bios_new=bios.copy()

In [67]:
bios_new['first_name']=bios_new['name'].str.split(' ').str[0]

In [68]:
bios_new

,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [69]:
bios_new.to_csv('./data/bios.csv')