### Adding/Removing Column

In [1]:
import pandas as pd

In [2]:
bios=pd.read_csv('./data/bios.csv')
bios['height_catogery']=bios['height_cm'].apply( lambda x: 'Short' if x < 165 else ('Average' if x<185 else 'Tall') )

In [3]:
bios.head()

,Unnamed: 0.1,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,height_catogery
0,0,0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Tall
1,1,1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Average
2,2,2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Average
3,3,3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Average
4,4,4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Tall

In [4]:
def categorize_athelete(row):
    if row['height_cm']< 175 and row['weight_kg'] <70:
        return 'Lightweight'
    elif  row['height_cm']< 185 or row['weight_kg'] <80:
        return 'Middleweight'
    else:
        return 'Heavyweight'
    
bios['Category']=bios.apply(categorize_athelete,axis=1)

In [5]:
bios.head()

,Unnamed: 0.1,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,height_catogery,Category
0,0,0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Tall,Heavyweight
1,1,1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Average,Middleweight
2,2,2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Average,Middleweight
3,3,3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Average,Lightweight
4,4,4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Tall,Heavyweight

## Mearging and Concatenating data

In [6]:
nocs=pd.read_csv('./data/noc_regions.csv')

In [7]:
bios_new=pd.merge(bios,nocs,left_on='born_country',right_on='NOC',how='left')

In [8]:
bios_new.rename(columns={'region':'born_country_full'},inplace='True')

In [9]:
bios_new.head()

,Unnamed: 0.1,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,height_catogery,Category,NOC_y,born_country_full,notes
0,0,0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Tall,Heavyweight,FRA,France,NaN
1,1,1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Average,Middleweight,FRA,France,NaN
2,2,2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Average,Middleweight,FRA,France,NaN
3,3,3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Average,Lightweight,FRA,France,NaN
4,4,4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Tall,Heavyweight,GBR,UK,NaN

In [10]:
bios_new[bios_new['NOC_x']!= bios_new['born_country_full']] [['name','NOC_x','born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [11]:
india=bios[bios['born_country']=='IND'].copy()
russia=bios[bios['born_country']=='RUS'].copy()

In [12]:
india

,Unnamed: 0.1,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,height_catogery,Category
80,80,80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21,George,Tall,Heavyweight
101,101,101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21,Algernon,Tall,Heavyweight
270,270,270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01,Nora,Tall,Heavyweight
273,273,273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN,Zeeshan,Average,Middleweight
274,274,274,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN,Anand,Tall,Middleweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140286,140286,140286,143790,Bajrang Punia,1994-02-26,Khudan,Haryana,IND,India,NaN,NaN,NaN,Bajrang,Tall,Heavyweight
140287,140287,140287,143791,Deepak Punia,1999-05-19,Jhajjar,Haryana,IND,India,NaN,NaN,NaN,Deepak,Tall,Heavyweight
143996,143996,143996,147660,Sumit Nagal,1997-08-16,Jhajjar,Haryana,IND,India,NaN,NaN,NaN,Sumit,Tall,Heavyweight
144114,144114,144114,147784,Diksha Dagar,2000-12-14,Jhajjar,Haryana,IND,India,174.0,NaN,NaN,Diksha,Average,Middleweight
144757,144757,144757,148458,Arif Khan,1990-03-09,Gulmarg,Jammu and Kashmir,IND,India,NaN,NaN,NaN,Arif,Tall,Heavyweight

In [13]:
russia

,Unnamed: 0.1,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,height_catogery,Category
158,158,158,159,Robert Spies,1891-02-17,Moskva (Moscow),Moskva,RUS,Germany,NaN,NaN,1982-10-22,Robert,Tall,Heavyweight
686,686,686,689,Ulada Charniauskaya,1966-08-10,Biysk,Altay Kray,RUS,Belarus,NaN,NaN,NaN,Ulada,Tall,Heavyweight
2095,2095,2095,2105,Rita Galinovskaya,1968-04-19,Chita,Zabaykalsky Kray,RUS,Russian Federation,164.0,53.0,NaN,Rita,Short,Lightweight
2096,2096,2096,2106,Makhlukhanum Murzayeva,1966-10-04,Makhachkala,Respublika Dagestan,RUS,Russian Federation,NaN,NaN,NaN,Makhlukhanum,Tall,Heavyweight
2097,2097,2097,2107,Yelena Tutachikova-Dostay,1969-03-08,Toora-Khem,Respublika Tyva,RUS,Russian Federation,157.0,50.0,NaN,Yelena,Short,Lightweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145487,145487,145487,149214,Yekaterina Kosova,1996-04-25,Moskva (Moscow),Moskva,RUS,ROC,NaN,NaN,NaN,Yekaterina,Tall,Heavyweight
145493,145493,145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,Landysh,Tall,Heavyweight
145495,145495,145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,Average,Lightweight
145496,145496,145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,Average,Lightweight
145497,145497,145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,Short,Lightweight

In [14]:
new_df=pd.concat([india,russia])

In [15]:
new_df

,Unnamed: 0.1,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,height_catogery,Category
80,80,80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21,George,Tall,Heavyweight
101,101,101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21,Algernon,Tall,Heavyweight
270,270,270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01,Nora,Tall,Heavyweight
273,273,273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN,Zeeshan,Average,Middleweight
274,274,274,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN,Anand,Tall,Middleweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145487,145487,145487,149214,Yekaterina Kosova,1996-04-25,Moskva (Moscow),Moskva,RUS,ROC,NaN,NaN,NaN,Yekaterina,Tall,Heavyweight
145493,145493,145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,Landysh,Tall,Heavyweight
145495,145495,145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,Average,Lightweight
145496,145496,145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,Average,Lightweight
145497,145497,145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,Short,Lightweight

### Handling Null Values

In [39]:
coffee=pd.read_csv('./data/coffee.csv')

In [35]:
coffee.head()

         Day      Day.1 Coffee Type  Units Sold  price  revenue  price.1
0     Monday     Monday    Espresso        25.0   3.99    99.75     3.99
1     Monday     Monday       Latte        15.0   6.33    94.95     6.33
2    Tuesday    Tuesday    Espresso        30.0   3.99   119.70     3.99
3    Tuesday    Tuesday       Latte        20.0   6.33   126.60     6.33
4  Wednesday  Wednesday    Espresso        35.0   3.99   139.65     3.99

In [43]:
import numpy as np
coffee.loc[[0,1],'Units Sold']=np.nan

In [44]:
coffee

          Day      Day.1 Coffee Type  Units Sold  price  revenue  price.1
0      Monday     Monday    Espresso         NaN   3.99    99.75     3.99
1      Monday     Monday       Latte         NaN   6.33    94.95     6.33
2     Tuesday    Tuesday    Espresso        30.0   3.99   119.70     3.99
3     Tuesday    Tuesday       Latte        20.0   6.33   126.60     6.33
4   Wednesday  Wednesday    Espresso        35.0   3.99   139.65     3.99
5   Wednesday  Wednesday       Latte        25.0   6.33   158.25     6.33
6    Thursday   Thursday    Espresso        40.0   3.99   159.60     3.99
7    Thursday   Thursday       Latte        30.0   6.33   189.90     6.33
8      Friday     Friday    Espresso        45.0   3.99   179.55     3.99
9      Friday     Friday       Latte        35.0   6.33   221.55     6.33
10   Saturday   Saturday    Espresso        45.0   3.99   179.55     3.99
11   Saturday   Saturday       Latte        35.0   6.33   221.55     6.33
12     Sunday     Sunday    Espresso        45.0   3.99   179.55     3.99
13     Sunday     Sunday       Latte        35.0   6.33   221.55     6.33
14          1        NaN         NaN        10.0   6.33    63.30     6.33

In [45]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          15 non-null     str
 1   Day.1        14 non-null     str
 2   Coffee Type  14 non-null     str
 3   Units Sold   13 non-null     float64
 4   price        15 non-null     float64
 5   revenue      15 non-null     float64
 6   price.1      15 non-null     float64
dtypes: float64(4), str(3)
memory usage: 1.2 KB

In [46]:
coffee.fillna(10000)

          Day      Day.1 Coffee Type  Units Sold  price  revenue  price.1
0      Monday     Monday    Espresso     10000.0   3.99    99.75     3.99
1      Monday     Monday       Latte     10000.0   6.33    94.95     6.33
2     Tuesday    Tuesday    Espresso        30.0   3.99   119.70     3.99
3     Tuesday    Tuesday       Latte        20.0   6.33   126.60     6.33
4   Wednesday  Wednesday    Espresso        35.0   3.99   139.65     3.99
5   Wednesday  Wednesday       Latte        25.0   6.33   158.25     6.33
6    Thursday   Thursday    Espresso        40.0   3.99   159.60     3.99
7    Thursday   Thursday       Latte        30.0   6.33   189.90     6.33
8      Friday     Friday    Espresso        45.0   3.99   179.55     3.99
9      Friday     Friday       Latte        35.0   6.33   221.55     6.33
10   Saturday   Saturday    Espresso        45.0   3.99   179.55     3.99
11   Saturday   Saturday       Latte        35.0   6.33   221.55     6.33
12     Sunday     Sunday    Espresso        45.0   3.99   179.55     3.99
13     Sunday     Sunday       Latte        35.0   6.33   221.55     6.33
14          1      10000       10000        10.0   6.33    63.30     6.33

In [47]:
coffee.fillna(coffee['Units Sold'].mean())

          Day      Day.1 Coffee Type  Units Sold  price  revenue  price.1
0      Monday     Monday    Espresso   33.076923   3.99    99.75     3.99
1      Monday     Monday       Latte   33.076923   6.33    94.95     6.33
2     Tuesday    Tuesday    Espresso   30.000000   3.99   119.70     3.99
3     Tuesday    Tuesday       Latte   20.000000   6.33   126.60     6.33
4   Wednesday  Wednesday    Espresso   35.000000   3.99   139.65     3.99
5   Wednesday  Wednesday       Latte   25.000000   6.33   158.25     6.33
6    Thursday   Thursday    Espresso   40.000000   3.99   159.60     3.99
7    Thursday   Thursday       Latte   30.000000   6.33   189.90     6.33
8      Friday     Friday    Espresso   45.000000   3.99   179.55     3.99
9      Friday     Friday       Latte   35.000000   6.33   221.55     6.33
10   Saturday   Saturday    Espresso   45.000000   3.99   179.55     3.99
11   Saturday   Saturday       Latte   35.000000   6.33   221.55     6.33
12     Sunday     Sunday    Espresso   45.000000   3.99   179.55     3.99
13     Sunday     Sunday       Latte   35.000000   6.33   221.55     6.33
14          1  33.076923   33.076923   10.000000   6.33    63.30     6.33

In [54]:
coffee.loc[[2,3],'Units Sold']=np.nan

In [49]:
coffee.loc[[0,1],'Units Sold']=15

In [51]:
coffee['Units Sold']=coffee['Units Sold'].interpolate()

In [52]:
coffee

          Day      Day.1 Coffee Type  Units Sold  price  revenue  price.1
0      Monday     Monday    Espresso   15.000000   3.99    99.75     3.99
1      Monday     Monday       Latte   15.000000   6.33    94.95     6.33
2     Tuesday    Tuesday    Espresso   21.666667   3.99   119.70     3.99
3     Tuesday    Tuesday       Latte   28.333333   6.33   126.60     6.33
4   Wednesday  Wednesday    Espresso   35.000000   3.99   139.65     3.99
5   Wednesday  Wednesday       Latte   25.000000   6.33   158.25     6.33
6    Thursday   Thursday    Espresso   40.000000   3.99   159.60     3.99
7    Thursday   Thursday       Latte   30.000000   6.33   189.90     6.33
8      Friday     Friday    Espresso   45.000000   3.99   179.55     3.99
9      Friday     Friday       Latte   35.000000   6.33   221.55     6.33
10   Saturday   Saturday    Espresso   45.000000   3.99   179.55     3.99
11   Saturday   Saturday       Latte   35.000000   6.33   221.55     6.33
12     Sunday     Sunday    Espresso   45.000000   3.99   179.55     3.99
13     Sunday     Sunday       Latte   35.000000   6.33   221.55     6.33
14          1        NaN         NaN   10.000000   6.33    63.30     6.33

In [55]:
coffee[coffee['Units Sold'].isna()]

       Day    Day.1 Coffee Type  Units Sold  price  revenue  price.1
2  Tuesday  Tuesday    Espresso         NaN   3.99    119.7     3.99
3  Tuesday  Tuesday       Latte         NaN   6.33    126.6     6.33

In [56]:
coffee[coffee['Units Sold'].notna()]

          Day      Day.1 Coffee Type  Units Sold  price  revenue  price.1
0      Monday     Monday    Espresso        15.0   3.99    99.75     3.99
1      Monday     Monday       Latte        15.0   6.33    94.95     6.33
4   Wednesday  Wednesday    Espresso        35.0   3.99   139.65     3.99
5   Wednesday  Wednesday       Latte        25.0   6.33   158.25     6.33
6    Thursday   Thursday    Espresso        40.0   3.99   159.60     3.99
7    Thursday   Thursday       Latte        30.0   6.33   189.90     6.33
8      Friday     Friday    Espresso        45.0   3.99   179.55     3.99
9      Friday     Friday       Latte        35.0   6.33   221.55     6.33
10   Saturday   Saturday    Espresso        45.0   3.99   179.55     3.99
11   Saturday   Saturday       Latte        35.0   6.33   221.55     6.33
12     Sunday     Sunday    Espresso        45.0   3.99   179.55     3.99
13     Sunday     Sunday       Latte        35.0   6.33   221.55     6.33
14          1        NaN         NaN        10.0   6.33    63.30     6.33